/* ==========================================================================
 * Program:        Email Prioritization System (List-Based MaxHeap)
 * Description:    Reads a stream of commands from standard input and maintains
 *                 a priority queue of the CEO's unread emails.  The priority
 *                 queue is a MaxHeap built entirely from scratch on top of a
 *                 singly linked list (no arrays are used to store the heap and
 *                 no library priority-queue code is used).  Emails are ordered
 *                 first by sender category (Boss > Subordinate > Peer >
 *                 ImportantPerson > OtherPerson) and, for equal categories, by
 *                 date with the newest email being the most important.
 * Inputs:         Commands on stdin, one per line:
 *                     EMAIL <category>,<subject>,<MM-DD-YYYY>  -- enqueue
 *                     NEXT                                     -- peek at top
 *                     READ                                     -- remove top
 *                     COUNT                                    -- print count
 * Outputs:        Printed to stdout: the "Next email:" block for NEXT and the
 *                 "There are N emails to read." line for COUNT.  EMAIL and
 *                 READ produce no output, as do NEXT/READ on an empty queue.
 * Collaborators:  None
 * Other Sources:  Initial draft generated by GenAI (Claude, Anthropic) from a
 *                 written specification, then reviewed, tested, and revised
 *                 by the author (bug fix to the blank-line output format;
 *                 verified against the assignment's sample test and edge
 *                 cases such as empty-queue NEXT/READ and consecutive
 *                 NEXT/READ commands).
 * Author:         David Joslin
 * Creation Date:  09/17/2026
 * Revision Date:  09/17/2026
 * Revisions:      Reworked printNext()/printCount() to separate output blocks
 *                 with a leading blank line (tracked via a "first output"
 *                 flag) instead of a trailing blank line, which fixed a bug
 *                 where the program printed an extra blank line after the
 *                 final command in a run.  Added per-line comments to
 *                 trim(), dateToKey(), splitEmailFields(), handleEmailCommand(),
 *                 and main() so every line's purpose is documented, not just
 *                 each function as a block.
 * Compile:        gcc email_prioritizer.c -o email_prioritizer
 * ========================================================================== */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* --------------------------------------------------------------------------
 * Fixed sizes and category ranking constants
 * -------------------------------------------------------------------------- */
#define MAX_LINE 1024   /* maximum length of one input line                  */
#define MAX_FIELD 512   /* maximum length of one comma-delimited field       */
#define NUM_CATEGORIES 5

/* Sender categories listed from highest priority to lowest priority.  The
 * rank of a category is derived from its position in this table, so the table
 * order is the single place that defines the category ordering. */
static const char *CATEGORY_NAMES[NUM_CATEGORIES] = {
    "Boss",            /* rank 5 - highest */
    "Subordinate",     /* rank 4 */
    "Peer",            /* rank 3 */
    "ImportantPerson", /* rank 2 */
    "OtherPerson"      /* rank 1 - lowest  */
};

/* --------------------------------------------------------------------------
 * Email: the payload stored in every heap node.
 * -------------------------------------------------------------------------- */
typedef struct Email {
    char sender[MAX_FIELD];  /* sender category string, exactly as supplied  */
    char subject[MAX_FIELD]; /* subject line (may contain spaces)            */
    char date[MAX_FIELD];    /* date string in MM-DD-YYYY form               */
    int rank;                /* numeric category priority: 5 = Boss .. 1     */
    long dateKey;            /* YYYYMMDD as an integer for easy comparison   */
} Email;

/* --------------------------------------------------------------------------
 * HeapNode / MaxHeap: the list-based heap itself.
 *
 * The heap is a complete binary tree stored as a singly linked list in
 * level order.  Node 0 is the root; for the node at position i the parent
 * lives at (i - 1) / 2 and the children live at 2i + 1 and 2i + 2.  Those
 * positions are reached by walking the list, which is what makes this a
 * list-based rather than an array-based implementation.
 * -------------------------------------------------------------------------- */
typedef struct HeapNode {
    Email data;             /* the email held by this node                   */
    struct HeapNode *next;  /* next node in level order                      */
} HeapNode;

typedef struct MaxHeap {
    HeapNode *head;         /* first node (the root of the heap)             */
    HeapNode *tail;         /* last node in level order, for O(1) appends    */
    int size;               /* number of emails currently in the heap        */
} MaxHeap;

/* --------------------------------------------------------------------------
 * Function prototypes
 * -------------------------------------------------------------------------- */
static void heapInit(MaxHeap *heap);
static void heapDestroy(MaxHeap *heap);
static HeapNode *heapNodeAt(const MaxHeap *heap, int index);
static void heapInsert(MaxHeap *heap, Email email);
static int heapPeek(const MaxHeap *heap, Email *out);
static void heapRemoveTop(MaxHeap *heap);
static void siftUp(MaxHeap *heap, int index);
static void siftDown(MaxHeap *heap, int index);
static int higherPriority(const Email *a, const Email *b);
static void swapEmails(Email *a, Email *b);
static int categoryRank(const char *category);
static long dateToKey(const char *date);
static void trim(char *text);
static int splitEmailFields(const char *body, char *sender, char *subject, char *date);
static void handleEmailCommand(MaxHeap *heap, const char *body);
static void printNext(const MaxHeap *heap);
static void printCount(const MaxHeap *heap);

/* ==========================================================================
 * Heap construction and teardown
 * ========================================================================== */

/* Put a heap into the well-defined empty state. */
static void heapInit(MaxHeap *heap)
{
    heap->head = NULL;
    heap->tail = NULL;
    heap->size = 0;
}

/* Free every node in the heap so the program leaks no memory. */
static void heapDestroy(MaxHeap *heap)
{
    HeapNode *current = heap->head;

    while (current != NULL) {
        HeapNode *doomed = current; /* remember the node being released      */
        current = current->next;    /* advance before freeing                */
        free(doomed);
    }

    heapInit(heap);
}

/* ==========================================================================
 * Positional access: the bridge between heap index arithmetic and the list
 * ========================================================================== */

/* Walk the list and return the node sitting at the given level-order index,
 * or NULL when the index is outside the heap. */
static HeapNode *heapNodeAt(const MaxHeap *heap, int index)
{
    HeapNode *current = heap->head;
    int position = 0;

    if (index < 0 || index >= heap->size) {
        return NULL; /* index does not exist in this heap                    */
    }

    while (current != NULL && position < index) {
        current = current->next;
        position++;
    }

    return current;
}

/* ==========================================================================
 * Priority comparison helpers
 * ========================================================================== */

/* Translate a sender category string into its numeric rank.  Unknown
 * categories rank below every known category so that bad input can never
 * outrank a legitimate email. */
static int categoryRank(const char *category)
{
    int i;

    for (i = 0; i < NUM_CATEGORIES; i++) {
        if (strcmp(category, CATEGORY_NAMES[i]) == 0) {
            /* First entry is the highest rank, hence the subtraction. */
            return NUM_CATEGORIES - i;
        }
    }

    return 0; /* unrecognized category                                       */
}

/* Convert an MM-DD-YYYY date string into a single comparable integer of the
 * form YYYYMMDD.  Digits are gathered in order and the separators are simply
 * ignored, so the routine is tolerant of stray spaces around the date. */
static long dateToKey(const char *date)
{
    int digits[8]; /* MM DD YYYY = 8 digits                                  */
    int found = 0;  /* number of digit characters collected so far           */
    int i;          /* index into the raw date string                       */
    long month = 0; /* two-digit month reassembled from digits[0..1]         */
    long day = 0;   /* two-digit day reassembled from digits[2..3]           */
    long year = 0;  /* four-digit year reassembled from digits[4..7]         */

    for (i = 0; date[i] != '\0' && found < 8; i++) {
        /* Only digit characters matter; '-' and any stray spaces are
         * skipped automatically by simply not being added to digits[]. */
        if (date[i] >= '0' && date[i] <= '9') {
            digits[found++] = date[i] - '0'; /* store the digit, advance     */
        }
    }

    if (found < 8) {
        return 0; /* malformed date: treat as the oldest possible date       */
    }

    month = digits[0] * 10L + digits[1];   /* combine the two month digits   */
    day = digits[2] * 10L + digits[3];     /* combine the two day digits     */
    year = ((digits[4] * 10L + digits[5]) * 10L + digits[6]) * 10L + digits[7];
    /* year built one digit at a time above so no single intermediate value
     * can overflow before it is scaled by its place value.                 */

    return year * 10000L + month * 100L + day; /* YYYYMMDD ordering          */
}

/* Return 1 when email a must sit above email b in the heap.  Category rank
 * dominates; a tie is broken in favour of the newer date. */
static int higherPriority(const Email *a, const Email *b)
{
    if (a->rank != b->rank) {
        return a->rank > b->rank;
    }

    return a->dateKey > b->dateKey; /* newest email wins the tie             */
}

/* Exchange the payloads of two nodes.  Only the data moves, never the links,
 * which keeps the level-order structure of the list intact. */
static void swapEmails(Email *a, Email *b)
{
    Email temp = *a;
    *a = *b;
    *b = temp;
}

/* ==========================================================================
 * Core heap operations
 * ========================================================================== */

/* Restore the heap property by moving a node upward toward the root. */
static void siftUp(MaxHeap *heap, int index)
{
    while (index > 0) {
        int parentIndex = (index - 1) / 2;
        HeapNode *child = heapNodeAt(heap, index);
        HeapNode *parent = heapNodeAt(heap, parentIndex);

        if (child == NULL || parent == NULL) {
            return; /* defensive: should not happen for valid indices        */
        }

        /* Stop as soon as the child no longer outranks its parent. */
        if (!higherPriority(&child->data, &parent->data)) {
            return;
        }

        swapEmails(&child->data, &parent->data);
        index = parentIndex; /* continue from the parent's position          */
    }
}

/* Restore the heap property by moving a node downward toward the leaves. */
static void siftDown(MaxHeap *heap, int index)
{
    while (1) {
        int leftIndex = 2 * index + 1;
        int rightIndex = 2 * index + 2;
        int bestIndex = index;
        HeapNode *bestNode = heapNodeAt(heap, index);
        HeapNode *leftNode = heapNodeAt(heap, leftIndex);
        HeapNode *rightNode = heapNodeAt(heap, rightIndex);
        HeapNode *chosenNode = NULL;

        if (bestNode == NULL) {
            return; /* nothing to sift                                       */
        }

        /* Pick whichever of the node and its two children ranks highest. */
        if (leftNode != NULL && higherPriority(&leftNode->data, &bestNode->data)) {
            bestIndex = leftIndex;
            bestNode = leftNode;
        }
        if (rightNode != NULL && higherPriority(&rightNode->data, &bestNode->data)) {
            bestIndex = rightIndex;
            bestNode = rightNode;
        }

        if (bestIndex == index) {
            return; /* the heap property already holds here                  */
        }

        chosenNode = heapNodeAt(heap, index);
        swapEmails(&chosenNode->data, &bestNode->data);
        index = bestIndex; /* follow the email that was pushed down          */
    }
}

/* Add one email to the heap: append it as the new last node in level order
 * and then sift it up into its correct place. */
static void heapInsert(MaxHeap *heap, Email email)
{
    HeapNode *node = (HeapNode *)malloc(sizeof(HeapNode));

    if (node == NULL) {
        return; /* out of memory: drop the email rather than crash           */
    }

    node->data = email;
    node->next = NULL;

    if (heap->head == NULL) {
        heap->head = node; /* first node becomes the root                    */
    } else {
        heap->tail->next = node;
    }
    heap->tail = node;
    heap->size++;

    siftUp(heap, heap->size - 1); /* bubble the newcomer up                  */
}

/* Copy the highest-priority email into *out.  Returns 0 for an empty heap. */
static int heapPeek(const MaxHeap *heap, Email *out)
{
    if (heap->size == 0 || heap->head == NULL) {
        return 0;
    }

    *out = heap->head->data;
    return 1;
}

/* Remove the highest-priority email.  The last node's payload is moved into
 * the root, the last node is unlinked and freed, and the new root is sifted
 * down.  Removing from an empty heap does nothing. */
static void heapRemoveTop(MaxHeap *heap)
{
    HeapNode *last = NULL;

    if (heap->size == 0 || heap->head == NULL) {
        return; /* empty queue: silently ignore                              */
    }

    if (heap->size == 1) {
        free(heap->head); /* the root is also the last node                  */
        heapInit(heap);
        return;
    }

    last = heap->tail;
    heap->head->data = last->data;        /* promote the last email          */
    heap->tail = heapNodeAt(heap, heap->size - 2); /* new last node          */
    heap->tail->next = NULL;              /* detach the node being removed   */
    free(last);
    heap->size--;

    siftDown(heap, 0); /* push the promoted email back down                  */
}

/* ==========================================================================
 * Input parsing helpers
 * ========================================================================== */

/* Remove leading and trailing whitespace from a string in place. */
static void trim(char *text)
{
    size_t start = 0;              /* index of the first non-blank char     */
    size_t end;                    /* index just past the last non-blank    */
    size_t length = strlen(text);  /* original length of the string         */

    while (start < length &&
           (text[start] == ' ' || text[start] == '\t' ||
            text[start] == '\r' || text[start] == '\n')) {
        start++; /* skip one more leading whitespace character              */
    }

    end = length; /* begin scanning for trailing whitespace from the end    */
    while (end > start &&
           (text[end - 1] == ' ' || text[end - 1] == '\t' ||
            text[end - 1] == '\r' || text[end - 1] == '\n')) {
        end--; /* drop one more trailing whitespace character                */
    }

    /* Shift the surviving characters to the front and terminate. */
    memmove(text, text + start, end - start); /* close the leading gap      */
    text[end - start] = '\0';                 /* cut off the trailing part  */
}

/* Split the body of an EMAIL command ("category,subject,date") into its three
 * fields.  The subject may contain spaces but no commas, so splitting on the
 * first and last comma is unambiguous.  Any spaces that follow a comma are
 * trimmed away, so both "A,B,C" and "A, B, C" parse identically.
 * Returns 1 on success and 0 when the body is malformed. */
static int splitEmailFields(const char *body, char *sender, char *subject, char *date)
{
    const char *firstComma = strchr(body, ',');  /* end of the sender field  */
    const char *secondComma = NULL;               /* end of the subject field */
    size_t senderLength;   /* number of characters in the sender field       */
    size_t subjectLength;  /* number of characters in the subject field      */

    if (firstComma == NULL) {
        return 0; /* no field separators at all                              */
    }

    secondComma = strchr(firstComma + 1, ','); /* look past the first comma  */
    if (secondComma == NULL) {
        return 0; /* only two fields supplied                                */
    }

    senderLength = (size_t)(firstComma - body);               /* body..first */
    subjectLength = (size_t)(secondComma - (firstComma + 1)); /* first..second */

    /* Guard against overrunning the destination buffers. */
    if (senderLength >= MAX_FIELD || subjectLength >= MAX_FIELD ||
        strlen(secondComma + 1) >= MAX_FIELD) {
        return 0; /* reject rather than truncate or overflow                 */
    }

    memcpy(sender, body, senderLength);   /* copy the sender field's bytes   */
    sender[senderLength] = '\0';          /* NUL-terminate the sender copy   */
    memcpy(subject, firstComma + 1, subjectLength); /* copy the subject text */
    subject[subjectLength] = '\0';        /* NUL-terminate the subject copy  */
    strcpy(date, secondComma + 1);        /* everything after the 2nd comma */

    trim(sender);   /* drop stray whitespace left around the sender field    */
    trim(subject);  /* drop stray whitespace left around the subject field   */
    trim(date);     /* drop stray whitespace/newline left around the date    */

    return 1; /* all three fields extracted successfully                    */
}

/* Build an Email from the text of an EMAIL command and insert it. */
static void handleEmailCommand(MaxHeap *heap, const char *body)
{
    Email email;                 /* the record that will be inserted        */
    char sender[MAX_FIELD];      /* scratch buffer for the sender field     */
    char subject[MAX_FIELD];     /* scratch buffer for the subject field    */
    char date[MAX_FIELD];        /* scratch buffer for the date field       */

    if (!splitEmailFields(body, sender, subject, date)) {
        return; /* ignore malformed EMAIL lines                              */
    }

    strcpy(email.sender, sender);   /* copy the parsed sender into the record */
    strcpy(email.subject, subject); /* copy the parsed subject into the record */
    strcpy(email.date, date);       /* copy the parsed date into the record  */
    email.rank = categoryRank(sender);   /* precompute the category priority */
    email.dateKey = dateToKey(date);     /* precompute the sortable date     */

    heapInsert(heap, email); /* place the fully-built record into the heap  */
}

/* ==========================================================================
 * Output helpers
 * ========================================================================== */

/* Tracks whether any NEXT/COUNT output has been printed yet.  A blank line
 * is printed BEFORE a block (rather than after) whenever this is false, so
 * report blocks are separated without leaving a trailing blank line after
 * the final command in a run.  (Author's fix: the GenAI-generated draft
 * printed a trailing blank line after every block, which produced one
 * extra blank line at the end of output whenever the last command was
 * NEXT or COUNT.) */
static int firstOutputPrinted = 0;

/* Print the highest-priority email, or nothing at all when none exists. */
static void printNext(const MaxHeap *heap)
{
    Email top;

    if (!heapPeek(heap, &top)) {
        return; /* empty queue produces no output                            */
    }

    if (firstOutputPrinted) {
        printf("\n"); /* separate this block from the previous one           */
    }
    printf("Next email:\n");
    printf("\tSender: %s\n", top.sender);
    printf("\tSubject: %s\n", top.subject);
    printf("\tDate: %s\n", top.date);
    firstOutputPrinted = 1;
}

/* Print how many emails remain unread. */
static void printCount(const MaxHeap *heap)
{
    if (firstOutputPrinted) {
        printf("\n"); /* separate this block from the previous one           */
    }
    printf("There are %d emails to read.\n", heap->size);
    firstOutputPrinted = 1;
}

/* ==========================================================================
 * main: read commands until end of input and dispatch each one
 * ========================================================================== */
int main(void)
{
    MaxHeap heap;          /* the CEO's priority queue of unread emails      */
    char line[MAX_LINE];   /* buffer for one line read from stdin            */

    heapInit(&heap); /* start with an empty queue                           */

    while (fgets(line, sizeof(line), stdin) != NULL) { /* read until EOF    */
        char *command = line; /* alias so trim() can modify it in place      */

        trim(command); /* drop the newline and any stray whitespace          */

        if (command[0] == '\0') {
            continue; /* skip blank lines                                    */
        }

        /* Dispatch on the command keyword.  EMAIL carries a payload, the
         * other three commands stand alone. */
        if (strncmp(command, "EMAIL", 5) == 0) {
            handleEmailCommand(&heap, command + 5); /* skip past "EMAIL"     */
        } else if (strcmp(command, "NEXT") == 0) {
            printNext(&heap); /* show, but do not remove, the top email      */
        } else if (strcmp(command, "READ") == 0) {
            heapRemoveTop(&heap); /* silent removal                          */
        } else if (strcmp(command, "COUNT") == 0) {
            printCount(&heap); /* report how many emails remain unread       */
        }
        /* Unrecognized commands are ignored. */
    }

    heapDestroy(&heap); /* release every remaining node                      */
    return 0;           /* success                                          */
}
